name: testcontainers_core
description: >-
  Dart library for throwaway instances of anything that can run in a Docker container
11.0.4
homepage: https://github.com/mridang/testcontainers-dart
repository: https://github.com/mridang/testcontainers-dart
issue_tracker: https://github.com/mridang/testcontainers-dart/issues
documentation: https://github.com/mridang/testcontainers-dart
funding:
  - https://github.com/sponsors/mridang
topics:
  - testing
  - docker
  - containers
  - test-automation

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  archive: ^3.6.0
  http: ^1.2.0
  meta: ^1.12.0
  path: ^1.9.0
  uuid: ^4.4.0

dev_dependencies:
  lints: ^3.0.0
  mocktail: ^1.0.0
  test: ^1.25.0
